spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        id: https://trax/api
        jwk:
          jwk-set-uri: https://badask.eu.auth0.com/.well-known/jwks.json
          issuer-uri: https://badask.eu.auth0.com/
  logging:
    level:
      dev.riska.trax: DEBUG
      org:
        springframework:
          data:
            r2dbc: DEBUG
  jackson:
    date-format: "dd-MM-yyyy HH:mm:ss"
  r2dbc:
    url: "r2dbc:mysql://localhost/trax?serverTimezone=Europe/Oslo"
    username: "trax"
    password: "trax"
    initialization-mode: "always"